language: generic

sudo: required

# Only run test when committing to master branch.
branches:
  only:
    - 7.x-3.x

env:
  global:
    - AEGIR_HOSTING_VERSION=7.x-3.x
    - AEGIR_TESTS_VERSION=master

#env:
#  - test: Ubuntu 14.04 Apache
#    distribution: ubuntu
#    version: 14.04
#    init: /sbin/init
#    run_opts: ""

addons:
  hosts:
    - aegir.local.computer
    - sitetest.aegir.local.computer

services:
  - docker

before_install:
  # Get test scripts
  - git clone http://github.com/aegir-project/tests.git /home/travis/build/aegir-project/tests
  - cd /home/travis/build/aegir-project/tests
  - git checkout $AEGIR_TESTS_VERSION

  # Run docker prepare script.
  - cd /home/travis/build/aegir-project/tests/travis
  - sudo bash prepare-docker.sh

  # Get aegir/hostmaster and database images.
  - sudo docker pull aegir/hostmaster:local
  - sudo docker pull mariadb

script:

  # Tests are included in the docker-compose.yml file in the tests repo.
  # See https://github.com/aegir-project/tests/blob/master/travis/docker-compose.yml for the docker setup.
  # See https://github.com/aegir-project/dockerfiles/blob/master/docker-entrypoint-tests.sh for the script that runs the tests.
  # See https://github.com/aegir-project/tests for the behat tests.
  - sudo docker-compose -f docker-compose-hosting.yml run hostmaster --rm